- package-lock.json
- package.json
- src/route.ts
Support netlify functions. This may also result in AWS to work but will need additional testing
> fix(netlify): Support Netlify Functions

- package-lock.json
- package.json
- src/cli/commands/dev.ts
- src/route.ts
- src/utils/is-prod.ts
- src/utils/route/logger.ts
- src/utils/route/youch.ts
- Abstract code
- Fix hot reloading
> Minor Fixes and Improvements

- .eslintrc.json
- package-lock.json
- package.json
- src/cli/commands/dev.ts
- src/index.ts
- src/test.ts
- src/types/route.ts
- src/utils/find-routes.ts
- src/utils/import-route.ts
- tests/methods.ts
- tests/middleware.ts
- tests/plugins.ts
- tests/route.ts
- tests/runkit.ts
- tests/youch.ts
> Support Testing

- guides/guides.json
- guides/testing/ava.md
- guides/testing/jest.md
Add some minimal guides for testing, will need to be updated and cleaned up in the future.
Fixes #33 and #22
> Add Testing Guides

- package.json
- src/cli/commands/dev.ts
- src/helpers/pino-pretty.ts
- src/route.ts
- tests/helpers/pino-pretty.ts
Added a custom pino prettifier to make the logs pretty.
Fixes #3 #41
> Make development logs pretty

- src/route.ts
- tests/plugins/error-handler.ts
add an extra error handler for logging
Fixes #37
> fix(errors): log error when it occurs

- src/route.ts
- tests/plugins.ts
plugin sounds more natural than plugins
> feat(plugin): rename plugins to plugin

- guides/deployments/runkit.md
- guides/error-handling.md
- guides/getting-started.md
- guides/middleware.md
- guides/misc/apollo.md
- guides/plugins.md
- guides/query.md
- guides/routes.md
- website/src/pages/index.jsx
update documentation for 1.5 to the new hooks system
> Update documentation for v1.5

- guides/global.md
- guides/guides.json
- src/global.ts
- src/index.ts
- tests/global.ts
- tests/seeds/global/with/light.config.js
- tests/seeds/global/with/routes/index.ts
- tests/seeds/global/without/light.config.js
- tests/seeds/global/without/routes/index.ts
Set up a global config so that you can share things such as a logger or metrics
> fix(global): set up global config

- guides/global.md
- src/server.ts
inject the variables into the global state to make it easier to access
> fix(global): inject the global variables into the server

- src/utils/add-route.ts
- tests/utils/add-route.ts
support nested directory routes
> fix(nested): support nested directory routes

- package-lock.json
- package.json
- src/cli/commands/dev.ts
- src/index.ts
- src/router.ts
- src/server.ts
- src/utils/find-routes.ts
- src/utils/import-routes.ts
- tests/utils/import-routes.ts
Add an initial implementation of a router. Still need to update tests and documentation which can be done in another PR.
> fix(router): add initial working router

- examples/nextjs/package-lock.json
- examples/nextjs/package.json
- examples/nextjs/pages/api/index.js
- examples/nextjs/pages/index.jsx
> add nextjs example

- examples/typescript/package-lock.json
- examples/typescript/package.json
- examples/typescript/routes/index.ts
- examples/typescript/tsconfig.json
- packages/light/package-lock.json
- packages/light/package.json
- packages/light/src/cli/commands/dev.ts
- packages/light/src/cli/commands/start.ts
- packages/light/src/use-global.ts
- packages/light/src/utils/find-routes.ts
- packages/light/src/utils/import-config.ts
- packages/light/tsconfig.json
Pretty simple, just imports ts-node if the typescript flag is provided
> Add support for typescript

- packages/light/jest.config.js
- packages/light/package.json
- packages/light/src/__tests__/create-route/index.test.ts
- packages/light/src/__tests__/create-route/seeds/with-plugin-and-middleware/routes/index.ts
- packages/light/src/create-route.ts
- website/docs/core/routes.mdx
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Send context to plugins instead of req, res
> Fix Plugins

- packages/light/src/__tests__/create-route/connect.test.ts
- packages/light/src/__tests__/create-route/seeds/with-connect/routes/index.ts
- packages/light/src/create-route.ts
- packages/light/src/types/route.ts
Inspired by https://nextjs.org/docs/api-routes/api-middlewares#connectexpress-middleware-support
related to #16
> Add basic connect support

- .github/workflows/main.yml
- .github/workflows/pr.yml
- benchmark/dangerfile.js
- benchmark/express.js
- benchmark/fastify.js
- benchmark/koa.js
- benchmark/package-lock.json
- benchmark/package.json
- benchmark/routes/index.js
- examples/basic/package-lock.json
- examples/basic/package.json
- examples/netlify/package-lock.json
- examples/netlify/package.json
- examples/nextjs/package-lock.json
- examples/nextjs/package.json
- examples/typescript/package-lock.json
- examples/typescript/package.json
- examples/vercel/package-lock.json
- examples/vercel/package.json
> Set up Benchmarking

- packages/@lightjs/cli/src/commands/dev.ts
- packages/@lightjs/cli/src/commands/start.ts
- packages/@lightjs/cli/src/middleware/youch.ts
- packages/@lightjs/core/package-lock.json
- packages/@lightjs/logger/src/useLogger/index.ts
- packages/@lightjs/types/src/config.ts
Part of https://github.com/ludicroushq/light/issues/1038
Renaming the config to be more clear
> Breaking Changes: Change Logger Config Name

- packages/light/src/index.ts
> Export Middleware

- packages/@lightjs/test/src/createTest/index.ts
#1038 
Better UX, so the user doesnt have to pass in an empty object every time
> Make createTest Options Optional
